const http=require("http"),fsp=require("fs/promises"),fs=require("fs"),path=require("path"),{exec}=require("child_process");
const VERSION="0.6.0",PORT=Number(process.env.DINOENGINE_PORT||4387),ROOT=path.resolve(process.env.DINOENGINE_ROOT||process.cwd()),MAX=15*1024*1024;
const RUNTIMES=[["node","--version"],["npm","--version"],["python","--version"],["py","--version"],["java","--version"],["javac","--version"],["gradle","--version"],["adb","--version"],["gcc","--version"],["git","--version"],["vercel","--version"],["netlify","--version"]];
const safe=p=>{const x=path.resolve(ROOT,p||"");if(x!==ROOT&&!x.startsWith(ROOT+path.sep))throw Error("Path escapes workspace");return x};
const out=(r,s,d)=>{const b=JSON.stringify(d,null,2);r.writeHead(s,{"Content-Type":"application/json","Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"});r.end(b)};
const body=q=>new Promise((ok,no)=>{let d="";q.on("data",c=>{d+=c;if(d.length>MAX)no(Error("Request too large"))});q.on("end",()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(Error("Invalid JSON"))}});q.on("error",no)});
const run=(c,cwd=ROOT,t=120000)=>new Promise(res=>exec(String(c),{cwd:safe(cwd),windowsHide:true,maxBuffer:25e6,timeout:Number(t)||120000},(e,stdout,stderr)=>res({ok:!e,code:e?.code??0,stdout,stderr})));
async function tree(dir=ROOT,rel=""){const a=[];for(const e of await fsp.readdir(dir,{withFileTypes:true})){if(["node_modules",".git","release",".dinoengine"].includes(e.name))continue;const p=path.join(rel,e.name);a.push({path:p.replaceAll(path.sep,"/"),type:e.isDirectory()?"folder":"file"});if(e.isDirectory())a.push(...await tree(path.join(dir,e.name),p))}return a}
async function filesWrite(files){if(!Array.isArray(files)||!files.length)throw Error("files required");const w=[];for(const x of files){const f=safe(x.path);await fsp.mkdir(path.dirname(f),{recursive:true});await fsp.writeFile(f,String(x.content??""),"utf8");w.push(x.path)}return{ok:true,written:w}}
async function git(c){return run("git "+c)}
async function runtimes(){const o={};for(const [n,c] of RUNTIMES)o[n]=await run(c,ROOT,10000);return o}

const uiDir=".dinoengine/ui";
async function uiRead(file){const p=safe(path.join(uiDir,file));try{return JSON.parse(await fsp.readFile(p,"utf8"))}catch(e){if(e.code==="ENOENT")return null;throw e}}
async function uiWrite(file,data){const p=safe(path.join(uiDir,file));await fsp.mkdir(path.dirname(p),{recursive:true});await fsp.writeFile(p,JSON.stringify(data,null,2),"utf8");return{ok:true,file:path.join(uiDir,file).replaceAll(path.sep,"/")}}
function svgFromPaint(strokes,w=1440,h=900){const esc=s=>String(s).replace(/&/g,"&amp;").replace(/"/g,"&quot;");let z=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}">`;for(const s of strokes||[]){if(!Array.isArray(s.points)||s.points.length<2)continue;z+=`<polyline fill="none" stroke="${esc(s.color||"#111")}" stroke-width="${Number(s.size||4)}" stroke-linecap="round" stroke-linejoin="round" points="${s.points.map(p=>p[0]+","+p[1]).join(" ")}"/>`}return z+"</svg>"}
async function paint(args){const canvas={name:String(args.name||"canvas"),width:Number(args.width||1440),height:Number(args.height||900),background:args.background||"transparent",strokes:args.strokes||[],updatedAt:new Date().toISOString()};return uiWrite("canvas-"+canvas.name+".json",canvas)}
async function animation(args){const a={name:String(args.name||"animation"),duration:Number(args.duration||1000),easing:String(args.easing||"ease"),tracks:Array.isArray(args.tracks)?args.tracks:[],updatedAt:new Date().toISOString()};return uiWrite("animation-"+a.name+".json",a)}
function cssAnimation(a){const frames=[];for(const t of a.tracks||[]){for(const k of t.keyframes||[])frames.push(k)}frames.sort((x,y)=>Number(x.at)-Number(y.at));let body="";for(const k of frames){const pct=(Number(k.at)/(a.duration||1000)*100).toFixed(2);const props=Object.entries(k.css||{}).map(([k,v])=>k+":"+v+";").join("");body+=pct+"%{"+props+"}"}return "@keyframes "+a.name+"{"+body+"}"}
async function exportAnimation(args){const a=await uiRead("animation-"+String(args.name)+".json");if(!a)throw Error("Animation not found");const css=cssAnimation(a);const file=String(args.file||"animations.css");await fsp.writeFile(safe(file),css,"utf8");return{ok:true,file,css}}
async function buildArtifact(args){const target=String(args.target||"").toLowerCase();const command=args.command||({exe:process.platform==="win32"?"npm run build && npm run package:win":"npm run build && npm run package",apk:"gradlew.bat assembleRelease",aab:"gradlew.bat bundleRelease"}[target]);if(!command)throw Error("Use target exe/apk/aab or provide command");return{target,result:await run(command,ROOT,Number(args.timeout)||600000)}}
async function websiteCreate(a){const n=String(a.name||"website").replace(/[^a-z0-9_-]/gi,"-").toLowerCase(),d=String(a.directory||n);await fsp.mkdir(safe(d),{recursive:true});return filesWrite((a.files||[]).map(x=>({path:path.posix.join(d,x.path),content:x.content})))}
async function publish(a){const p=String(a.provider||"github-pages");if(p==="github-pages"||p==="github"){const b=String(a.branch||"gh-pages");let r=await git("checkout "+JSON.stringify(b));if(!r.ok)r=await git("checkout -B "+JSON.stringify(b));if(!r.ok)return r;const c=await git("add -A && git commit -m "+JSON.stringify(a.message||"Publish website"));const push=await git("push -u origin "+JSON.stringify(b));return{provider:p,branch:b,commit:c,push}}if(p==="vercel")return run("vercel --prod --yes",ROOT,600000);if(p==="netlify")return run("netlify deploy --prod",ROOT,600000);throw Error("Unsupported provider")}

const S=t=>({type:t});
const TOOL_DEFS=[
["workspace_tree","List workspace",{}],["read_file","Read file",{path:S("string")}],["write_file","Write file",{path:S("string"),content:S("string")}],["write_files","Write many files",{files:{type:"array",items:{type:"object"}}}],["delete_file","Delete file",{path:S("string"),recursive:S("boolean")}],["make_folder","Create folder",{path:S("string")}],["run","Run command",{command:S("string"),cwd:S("string"),timeout:S("number")}],["runtimes","Detect runtimes",{}],["project_inspect","Inspect project",{}],["git_status","Git status",{}],["git_log","Git log",{}],["git_diff","Git diff",{}],["git_branch","Git branches",{}],["git_create_branch","Create branch",{name:S("string")}],["git_checkout","Checkout branch",{name:S("string")}],["git_commit","Commit changes",{message:S("string")}],["git_push","Push changes",{remote:S("string"),branch:S("string")}],["git_pull","Pull changes",{remote:S("string"),branch:S("string")}],
["website_create","Create a complete website from generated files",{name:S("string"),directory:S("string"),files:{type:"array",items:{type:"object"}}}],["website_publish","Publish website",{provider:{type:"string",enum:["github-pages","vercel","netlify"]},branch:S("string"),message:S("string")}],["deploy_command","Run deployment command",{command:S("string"),timeout:S("number")}],
["ui_paint","Store hand-drawn UI strokes for GPT to use as a visual design layer",{name:S("string"),width:S("number"),height:S("number"),background:S("string"),strokes:{type:"array"} }],
["ui_read","Read a saved UI canvas",{file:S("string")}],["ui_export_svg","Turn a saved paint canvas into SVG",{file:S("string"),output:S("string")}],
["animation_create","Create an animation timeline from keyframes",{name:S("string"),duration:S("number"),easing:S("string"),tracks:{type:"array"}}],["animation_read","Read an animation timeline",{name:S("string")}],["animation_export_css","Export animation timeline to CSS",{name:S("string"),file:S("string")}],
["build_artifact","Build an EXE, APK, AAB, or custom artifact",{target:S("string"),command:S("string"),timeout:S("number")}],
["engine_info","Get engine capabilities",{}]
].map(([name,description,properties])=>({name,description,inputSchema:{type:"object",properties,additionalProperties:true}}));

async function tool(n,a={}){
switch(n){
case"workspace_tree":return{root:ROOT,tree:await tree()};case"read_file":return{path:a.path,content:await fsp.readFile(safe(a.path),"utf8")};case"write_file":return filesWrite([{path:a.path,content:a.content}]);case"write_files":return filesWrite(a.files);case"delete_file":await fsp.rm(safe(a.path),{recursive:!!a.recursive,force:true});return{ok:true};case"make_folder":await fsp.mkdir(safe(a.path),{recursive:true});return{ok:true};case"run":return run(a.command,a.cwd||ROOT,a.timeout);case"runtimes":return runtimes();case"project_inspect":{const t=await tree();return{root:ROOT,fileCount:t.filter(x=>x.type==="file").length,hasGit:fs.existsSync(path.join(ROOT,".git")),files:t.filter(x=>x.type==="file").map(x=>x.path)}}case"git_status":return git("status --short --branch");case"git_log":return git("log --oneline -20");case"git_diff":return git("diff");case"git_branch":return git("branch");case"git_create_branch":return git("branch "+JSON.stringify(a.name));case"git_checkout":return git("checkout "+JSON.stringify(a.name));case"git_commit":return git("add -A && git commit -m "+JSON.stringify(a.message||"DinoEngine commit"));case"git_push":return git("push "+(a.remote||"origin")+" "+(a.branch||"HEAD"));case"git_pull":return git("pull "+(a.remote||"origin")+" "+(a.branch||""));case"website_create":return websiteCreate(a);case"website_publish":return publish(a);case"deploy_command":return run(a.command,ROOT,a.timeout||600000);
case"ui_paint":return paint(a);case"ui_read":return uiRead(a.file||("canvas-"+a.name+".json"));case"ui_export_svg":{const c=await uiRead(a.file);if(!c)throw Error("Canvas not found");const f=String(a.output||"ui-paint.svg");await fsp.writeFile(safe(f),svgFromPaint(c.strokes,c.width,c.height),"utf8");return{ok:true,file:f}}case"animation_create":return animation(a);case"animation_read":return uiRead("animation-"+a.name+".json");case"animation_export_css":return exportAnimation(a);case"build_artifact":return buildArtifact(a);case"engine_info":return{engine:"DinoEngine",version:VERSION,workspace:ROOT,protocol:"DinoMCP/1.0",capabilities:TOOL_DEFS.map(x=>x.name),gptIntegration:"MCP connector",artifacts:["exe","apk","aab","custom"],ui:["paint","svg","animation-timeline","css-keyframes"]};default:throw Error("Unknown tool: "+n)}}
async function mcp(req,res,b){const id=b.id??null;try{if(b.method==="initialize")return out(res,200,{jsonrpc:"2.0",id,result:{protocolVersion:"2025-06-18",serverInfo:{name:"DinoEngine",version:VERSION},capabilities:{tools:{}}}});if(b.method==="tools/list")return out(res,200,{jsonrpc:"2.0",id,result:{tools:TOOL_DEFS}});if(b.method==="tools/call"){const z=await tool(b.params?.name,b.params?.arguments||{});return out(res,200,{jsonrpc:"2.0",id,result:{content:[{type:"text",text:JSON.stringify(z,null,2)}],structuredContent:z}})}if(b.method==="ping")return out(res,200,{jsonrpc:"2.0",id,result:{}});return out(res,200,{jsonrpc:"2.0",id,error:{code:-32601,message:"Method not found"}})}catch(e){return out(res,200,{jsonrpc:"2.0",id,error:{code:-32000,message:e.message}})}}
async function route(q,r){const u=new URL(q.url,"http://localhost");if(q.method==="OPTIONS"){r.writeHead(204,{"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"Content-Type"});return r.end()}const b=["POST","PUT","PATCH","DELETE"].includes(q.method)?await body(q):{};if(q.method==="POST"&&u.pathname==="/mcp")return mcp(q,r,b);if(q.method==="GET"&&u.pathname==="/")return out(r,200,{engine:"DinoEngine",version:VERSION,workspace:ROOT,protocol:"DinoMCP/1.0",mcp:"/mcp",features:["GPT website builder","paint UI","animation timeline","EXE/APK/AAB build"]});if(q.method==="GET"&&u.pathname==="/api/health")return out(r,200,{ok:true,pid:process.pid,node:process.version,version:VERSION});if(q.method==="GET"&&u.pathname==="/api/tree")return out(r,200,await tool("workspace_tree"));if(q.method==="GET"&&u.pathname==="/api/runtime")return out(r,200,{runtimes:await runtimes()});if(q.method==="GET"&&u.pathname==="/api/file")return out(r,200,await tool("read_file",{path:u.searchParams.get("path")}));if(q.method==="POST"&&u.pathname==="/api/file")return out(r,200,await tool("write_file",b));if(q.method==="POST"&&u.pathname==="/api/run")return out(r,200,await tool("run",b));return out(r,404,{error:"Not found"})}
http.createServer((q,r)=>route(q,r).catch(e=>out(r,500,{error:e.message}))).listen(PORT,"127.0.0.1",()=>console.log("DinoEngine v"+VERSION+" | "+ROOT+" | http://127.0.0.1:"+PORT));